services:
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        env_file:
            - .env.dev
        volumes:
            - mongodb:/data/db
            - ./scripts/mongo-init:/docker-entrypoint-initdb.d

#    streamlit:
#        build: .
#        container_name: streamlit_app
#        depends_on:
#            - mongodb
#        ports:
#            - "8501:8501"
#
#        volumes:
#            - ./logs:/app/logs

volumes:
    mongodb:
        external: true
        # auf true umstellen für prod um volume nicht immer zu löschen 
